export const GET_DATA_GENERAL_INFORMATION = 'GET_DATA_GENERAL_INFORMATION';
export const NEWS_GENERAL_INFORMATION_RECEIVED = 'NEWS_GENERAL_INFORMATION_RECEIVED';
export const GET_DATA_GENARAL_INFORMATION_ERROR = 'GET_DATA_GENARAL_INFORMATION_ERROR';
export const NEWS_AOV_RECEIVED = 'NEWS_AOV_RECEIVED';
export const NEWS_GROWTH_RATE_RECEIVED = 'NEWS_GROWTH_RATE_RECEIVED';
export const NEWS_CUS_BY_CHANNEL_RECEIVED = 'NEWS_CUS_BY_CHANNEL_RECEIVED';
export const NEWS_RATE_BY_REGION_RECEIVED = 'NEWS_RATE_BY_REGION_RECEIVED';
