export const GET_DATA_TRACKING_BEHAVIOR = 'GET_DATA_TRACKING_BEHAVIOR';
export const NEWS_TRACKING_BEHAVIOR_RECEIVED = 'NEWS_TRACKING_BEHAVIOR_RECEIVED';
export const GET_DATA_TRACKING_BEHAVIOR_ERROR = 'GET_DATA_TRACKING_BEHAVIOR_ERROR';
