export const FETCH_USERS_ASYNC = 'FETCH_USERS_ASYNC';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FILTER_SEARCH = 'FILTER_SEARCH';

export const ADD_USERS = 'ADD_USERS';
export const ADD_USERS_SUCCESS = 'ADD_USERS_SUCCESS';
export const ADD_USERS_ERROR = 'ADD_USERS_ERROR';

export const DELETE_USERS = 'DELETE_USERS';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const DELETE_USERS_ERROR = 'DELETE_USERS_ERROR';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const ON_ACTIVE = 'ON_ACTIVE';
export const ON_ACTIVE_SUCCESS = 'ON_ACTIVE_SUCCESS';
export const ON_ACTIVE_ERROR = 'ON_ACTIVE_ERROR';

export const UPDATE_USERS = 'UPDATE_USERS';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const UPDATE_USERS_ERROR = 'UPDATE_USERS_ERROR';

export const DELETE_ID = 'DELETE_ID';
export const DELETE_ID_SUCCESS = 'DELETE_ID_SUCCESS';
export const DELETE_ID_ERROR = 'DELETE_ID_ERROR';

export const GET_USER_BY_ID_ASYNC = 'GET_USER_BY_ID_ASYNC';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
