export const GET_DATA_OVERVIEW = 'GET_DATA_OVERVIEW';
export const NEWS_OVERVIEW_RECEIVED = 'NEWS_OVERVIEW_RECEIVED';
export const GET_DATA_OVERVIEW_ERROR = 'GET_DATA_OVERVIEW_ERROR';
export const NEWS_OVERVIEW_FACEBOOK_RECEIVED = 'NEWS_OVERVIEW_FACEBOOK_RECEIVED';
export const NEWS_OVERVIEW_INSTAGRAM_RECEIVED = 'NEWS_OVERVIEW_INSTAGRAM_RECEIVED';
