import { makeStyles } from '@material-ui/core';

const useStyles = makeStyles((theme) => ({
  root: {
    '& .MuiDataGrid-root': {},
    '& .MuiDataGrid-columnHeaderTitle': {
      fontfamily: 'Inter',
      fontSize: 14,
      fontWeight: 600,
      color: '#6E6893',
      textAlign: 'left',
    },
    '& .MuiDataGrid-footerContainer': {
      '& .MuiDataGrid-selectedRowCount': {
        fontfamily: 'Inter',
        fontSize: 12,
        fontStyle: 'uppercase',
        fontWeight: 600,
        color: '#6E6893',
        textAlign: 'left',
      },
    },
    '& .MuiDataGrid-cell--textLeft': {
      fontfamily: 'Inter',
      fontSize: 14,
      fontStyle: 'normal',
      fontWeight: 500,
      textAlign: 'left',
    },
    '& .MuiTablePagination-caption': {
      fontfamily: 'Inter',
      fontSize: 12,
      fontStyle: 'normal',
      fontWeight: 700,
      textAlign: 'left',
      background: '#E6E6F2',
      color: '#4A4AFF',
    },
  },
  title: {
    fontfamily: 'Inter',
    fontSize: 28,
    fontStyle: 'normal',
    fontWeight: 700,
    color: '#8B83BA',
    textAlign: 'left',
    margin: theme.spacing(2, 0, 2, 0),
  },
  boxtext: {
    fontfamily: 'Inter',
    fontSize: 17,
    fontStyle: 'normal',
    fontWeight: 500,
    color: '#25213B',
    textAlign: 'left',
    marginTop: theme.spacing(1),
  },
  filter: {
    width: 112,
    height: 45,
    borderadius: 6,
    margin: theme.spacing(2, 1, 4, 0),
    color: '#1565D8',
    borderStyle: 'solid',
    borderWidth: 2,
  },
  titlebox: {
    fontfamily: 'Inter',
    fontSize: 20,
    color: '#25213B',
    fontStyle: 'normal',
    fontWeight: 700,
    textAlign: 'left',
  },
  desbox: {
    fontfamily: 'Inter',
    fontSize: 18,
    color: '#25213B',
    fontStyle: 'normal',
    fontWeight: 400,
    textAlign: 'left',
    margin: theme.spacing(2, 0, 0, 2),
  },
  search: {
    width: 445,
    height: 45,
    borderadius: 6,
    margin: theme.spacing(2, 0, 4, 0),
    background: '#F2F9FF',
    color: '#1565D8',
    borderStyle: 'solid',
    borderWidth: 1,
  },
  delete: {
    width: 112,
    height: 41,
    margin: theme.spacing(2),
    background: '#D81C1C',
    color: '#FFFFFF',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#D81C1C',
    '&:hover': {
      background: '#D81C1C',
    },
  },
  email: {
    fontfamily: 'Inter',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 400,
    textAlign: 'left',
    color: '#6E6893',
  },
  active: {
    width: 75,
    height: 20,
    borderRadius: 10,
    fontfamily: 'Inter',
    fontSize: 12,
    textTransform: 'capitalize',
    fontWeight: 500,
    textAlign: 'left',
    background: '#E6E6F2',
    color: '#4A4AFF',
  },
  inactive: {
    width: 75,
    height: 20,
    borderRadius: 10,
    fontfamily: 'Inter',
    textTransform: 'capitalize',
    fontSize: 12,
    fontWeight: 500,
    textAlign: 'left',
    background: '#F2F0F9',
    color: '#6E6893',
  },
  showmore: {
    width: 100,
    height: 24,
    fontfamily: 'Inter',
    fontSize: 12,
    fontWeight: 700,
    textAlign: 'left',
    color: '#6E6893',
    textTransform: 'capitalize',
    padding: theme.spacing(1),
    justifyContent: 'none',
  },
  new: {
    width: 112,
    height: 41,
    margin: theme.spacing(2, 2, 2, 0),
    background: '#007F00',
    color: '#FFFFFF',
    '&:hover': {
      background: '#007F00',
    },
  },
  boxsize: {
    width: '100%',
    color: '#979797',
  },
  viewMoreItem: {
    width: '134px',
    padding: theme.spacing(0.5),
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#F2F0F9',
      borderRadius: '4px',
    },
  },
  text: {
    padding: 10,
  },
  checkbox: {
    color: '#6D5BD0',
  },
  filterBtn: {
    width: 90,
    textTransform: 'none',
    backgroundColor: 'white',
    border: '1px solid #E2E8F0',
    fontWeight: 500,
    color: '#0096C7',
  },
  addBtn: {
    width: 157,
    marginLeft: theme.spacing(2),
    color: 'white',
    textTransform: 'none',
    fontWeight: 500,
    backgroundColor: '#0096C7',
    '&:hover': {
      backgroundColor: '#0077B6',
    },
  },
  textField: {
    width: '50%',
    height: 40,
    background: 'white',
    color: '#1565D8',
    '& .MuiOutlinedInput-root .MuiOutlinedInput-notchedOutline': {
      borderColor: '#E2E8F0',
    },
    '& .MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline': {
      borderColor: '#0096C7',
    },
    '&:hover .MuiOutlinedInput-root .MuiOutlinedInput-notchedOutline': {
      borderColor: '#0096C7',
    },
  },
  groupFilterButton: {
    padding: 10,
    textAlign: 'right',
    marginRight: 10,
  },
  titleFilter: {
    color: '#000000',
    padding: '10px 20px',
    fontWeight: 700,
  },
  fieldSelect: {
    height: 40,
    width: 344,
    marginLeft: '20px',
    background: 'white',
    '&.MuiOutlinedInput-root .MuiOutlinedInput-notchedOutline': {
      borderColor: '#E2E8F0',
    },
    '& .MuiOutlinedInput-input': {
      padding: '9px 10px',
    },
    '&.MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline': {
      borderColor: '#E2E8F0',
    },
  },
  select: {
    margin: '0px 10px',
    '& .MuiOutlinedInput-input': {
      padding: '5px 30px 5px 10px',
    },
  },
}));

export default useStyles;
