export const GET_DATA_FB = 'GET_DATA_FB';
export const NEWS_FB_RECEIVED = 'NEWS_FB_RECEIVED';
export const GET_DATA_FB_ERROR = 'GET_DATA_FB_ERROR';
export const NEWS_FB_PAGE_RECEIVED = 'NEWS_FB_PAGE_RECEIVED';
export const NEWS_FB_TOP_PAGE_RECEIVED = 'NEWS_FB_TOP_PAGE_RECEIVED';
